- name: installing haproxy
  apt:
    name: haproxy

- name: installing haproxyctl
  apt:
    name: haproxyctl

- name: apply configuration
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - restart haproxy
