execution:
- concurrency: 500
  throughput: 1000
  ramp-up: 1m
  hold-for: 5m
  scenario: stress

scenarios:
  stress:
    default-address: http://test.axnion.xyz
    requests:
    - url: /item
      method: GET

reporting:
- module: blazemeter
  token:
  report-name: Taurus test report
