execution:
- concurrency: 5
  throughput: 10
  ramp-up: 1m
  hold-for: 10m
  scenario: stress

scenarios:
  stress:
    default-address: http://test.axnion.xyz
    requests:
    - url: /item
      method: GET

reporting:
- module: blazemeter
  token:
  report-name: Taurus test report
