execution:
- concurrency: 265
  throughput: 260
  ramp-up: 30s
  hold-for: 5m
  scenario: stress

scenarios:
  stress:
    default-address: http://test.axnion.xyz
    requests:
    - url: /item
      method: GET

reporting:
- module: blazemeter
  token:
  report-name: Taurus test report
