---
- name: Installing pip
  apt:
    name: python-pip
    state: present

- name: Installing bzt
  pip:
    name: bzt

- name: Creating testing folder
  file:
    path: /home/vagrant/tests
    state: directory
    owner: vagrant

- name: Moving low test to server
  copy:
    src: low.yml
    dest: /home/vagrant/tests/low.yml
    owner: vagrant

- name: Moving medium test to server
  copy:
    src: medium.yml
    dest: /home/vagrant/tests/medium.yml
    owner: vagrant

- name: Moving high test to server
  copy:
    src: high.yml
    dest: /home/vagrant/tests/high.yml
    owner: vagrant
