# Deploy application
- name: download repository
  git:
    repo: https://github.com/axnion/haapp.git
    dest: "{{ install_path }}"
    force: yes

- name: apply application configuration
  template:
    src: config.js.j2
    dest: "{{ install_path }}/config.js"

- name: copy systemd configuration
  template:
    src: haapp.service.j2
    dest: /etc/systemd/system/haapp.service

- name: install dependencies
  command: npm install
  args:
    chdir: "{{ install_path }}"

- name: restart service
  systemd:
    name: haapp
    state: restarted
    daemon_reload: yes
    enabled: yes
