# For each blue server

# Create backups

# Remove application server from load balancers

# Remove datbase server from all application servers

# Apply changes to application server

# Migrate database

# Add databse server to new db cluster

# Connect application to new db cluster

# Smoke testing





# Deploy application
- name: download repository
  git:
    repo: https://github.com/axnion/haapp.git
    dest: "{{ install_path }}"
    force: yes

- name: apply application configuration
  template:
    src: config.js.j2
    dest: "{{ install_path }}/config.js"

- name: copy systemd configuration
  template:
    src: haapp.service.j2
    dest: /etc/systemd/system/haapp.service

- name: install dependencies
  command: npm install
  args:
    chdir: "{{ install_path }}"

- name: restart service
  systemd:
    name: haapp
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: debug pause
  pause:
    seconds: 30
