- name: adding key
  apt_key:
    url: https://www.apache.org/dist/cassandra/KEYS
    state: present

- name: adding repository
  apt_repository:
    repo: deb http://www.apache.org/dist/cassandra/debian 311x main
    state: present

- name: installing
  apt:
    name: cassandra
    update_cache: yes
    state: present
