- name: apply cassandra.yaml
  template:
    src: cassandra.yml.j2
    dest: /etc/cassandra/cassandra.yaml
  register: cassandra_config
  notify:
    - restart cassandra

- name: make users available anywhere
  command: "cqlsh -e \"ALTER KEYSPACE \"system_auth\" WITH REPLICATION = {'class': 'SimpleStrategy', 'replication_factor': 3};\" -u cassandra -p cassandra {{ hostvars[inventory_hostname]['ansible_host'] }}"
  retries: 5
  delay: 5
  register: result
  until: result.rc == 0
  when: cassandra_config.changed

- name: repair system_auth
  command: nodetool repair system_auth
  retries: 5
  delay: 5
  when: cassandra_config.changed
  register: result
  until: result.rc == 0
  notify:
    - restart cassandra

# TODO: Add user from vault
- name: add new user
  command: "cqlsh -e \"CREATE ROLE admin WITH PASSWORD = 'admin' AND SUPERUSER = true AND LOGIN = true;\" -u cassandra -p cassandra {{ hostvars[inventory_hostname]['ansible_host'] }}"
  retries: 5
  delay: 5
  register: result
  until: result.rc == 0
  when: cassandra_config.changed


- name: remove privileges of default user
  command: "cqlsh -e \"ALTER ROLE cassandra WITH PASSWORD = 'thisisaveryrandompasswordineedtochangesomeday' AND SUPERUSER = false;\" -u cassandra -p cassandra {{ hostvars[inventory_hostname]['ansible_host'] }}"
  retries: 5
  delay: 5
  register: result
  until: result.rc == 0
  when: cassandra_config.changed
