- name: Importing variables
  ignore_errors: true
  include_vars: vars.yml

# Disconnect from loadbalancers ------------------------------------------------
- name: Remove application server from load blancers
  ignore_errors: true
  command: haproxyctl disable server web/"{{ inventory_hostname }}"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['lb'] }}"

# Make sure directories exist --------------------------------------------------
- name: Create backup directory
  file:
    path: /opt/backups
    state: directory

- name: Create application directory
  file:
    path: /opt/haapp
    state: directory

# Backup app -------------------------------------------------------------------
- name: Create backups of application server
  ignore_errors: true
  archive:
    path: "{{ install_path }}"
    dest: "{{ backup_path }}/app_backup.tar.gz"
    format: gz

# Disconnect database from cluster ---------------------------------------------
- name: Disconnect database server from cluster
  ignore_errors: true
  command: nodetool "-h {{ hostvars[item]['ansible_host'] }} -u cassandra -pw cassandra"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['db'] }}"
  when: hostvars[item]['site'] == hostvars[inventory_hostname]['site']

# Stop services ----------------------------------------------------------------
- name: Stop application service
  ignore_errors: true
  systemd:
    name: haapp
    state: stopped

- name: Stop database service
  ignore_errors: true
  systemd:
    name: cassandra
    state: stopped
  delegate_to: "{{ item }}"
  with_items: "{{ groups['db'] }}"
  when: hostvars[item]['site'] == hostvars[inventory_hostname]['site']


# Download, install, and configure ---------------------------------------------
- name: Downloading repository
  ignore_errors: true
  git:
    repo: https://github.com/axnion/haapp.git
    dest: "{{ install_path }}"
    force: yes

- name: Applying application configuration
  ignore_errors: true
  template:
    src: config.js.j2
    dest: "{{ install_path }}/config.js"

- name: Copying systemd configuration
  ignore_errors: true
  template:
    src: haapp.service.j2
    dest: /etc/systemd/system/haapp.service

- name: Installing dependencies
  ignore_errors: true
  command: npm install
  args:
    chdir: "{{ install_path }}"

- name: Set application server to updated
  ignore_errors: true
  set_fact:
    updated: true

# Migrate database and connect to new cluster ----------------------------------
- name: Run database migration script
  ignore_errors: true
  command: echo "REPLACE ME"

- name: Copy new database configuration
  template:
    src: cassandra.yml.j2
    dest: /etc/cassandra/cassandra.yaml
  register: cassandra_config
  delegate_to: "{{ item }}"
  with_items: "{{ groups['db'] }}"
  when: hostvars[item]['site'] == hostvars[inventory_hostname]['site']

- name: Reconnect database server to new cluster
  ignore_errors: true
  command: echo "REPLACE ME"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['db'] }}"
  when: hostvars[item]['site'] == hostvars[inventory_hostname]['site']

# Starting services ------------------------------------------------------------
- name: Starting database service
  ignore_errors: true
  systemd:
    name: cassandra
    state: started
    enabled: yes
  delegate_to: "{{ item }}"
  with_items: "{{ groups['db'] }}"
  when: hostvars[item]['site'] == hostvars[inventory_hostname]['site']

- name: Starting service
  ignore_errors: true
  systemd:
    name: haapp
    state: started
    daemon_reload: yes
    enabled: yes

# Smoke test -------------------------------------------------------------------
- name: Smoke test
  command: "/opt/test.sh {{ inventory_hostname }}"
  ignore_errors: true
  register: smoke_test
