- name: Importing variables
  ignore_errors: true
  include_vars: vars.yml

# Disconnect from loadbalancers ------------------------------------------------
- name: Remove application server from load blancers
  ignore_errors: true
  command: echo "yaay"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['lb'] }}"

# Make sure directories exist --------------------------------------------------
- name: Create backup directory
  file:
    path: /opt/backups
    state: directory

- name: Create application directory
  file:
    path: /opt/haapp
    state: directory

# Backup app -------------------------------------------------------------------
- name: Create backups of application server
  ignore_errors: true
  archive:
    path: "{{ install_path }}"
    dest: "{{ backup_path }}/app_backup.tar.gz"
    format: gz

# Disconnect database from cluster ---------------------------------------------
- name: Disconnect database server from cluster
  ignore_errors: true
  command: echo "yaay"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['db'] }}"
  when: hostvars[item]['site'] == hostvars[inventory_hostname]['site']

# Stop service -----------------------------------------------------------------
- name: Stop service
  ignore_errors: true
  systemd:
    name: haapp
    state: stopped
    daemon_reload: yes
    enabled: yes

# Download, install, and configure ---------------------------------------------
- name: Downloading repository
  ignore_errors: true
  git:
    repo: https://github.com/axnion/haapp.git
    dest: "{{ install_path }}"
    force: yes

- name: Applying application configuration
  ignore_errors: true
  template:
    src: config.js.j2
    dest: "{{ install_path }}/config.js"

- name: Copying systemd configuration
  ignore_errors: true
  template:
    src: haapp.service.j2
    dest: /etc/systemd/system/haapp.service

- name: Installing dependencies
  ignore_errors: true
  command: npm install
  args:
    chdir: "{{ install_path }}"

# Migrate database and connect to new cluster ----------------------------------
- name: Run database migration script
  ignore_errors: true
  command: echo "REPLACE ME"

- name: Reconnect database server to new cluster
  ignore_errors: true
  command: echo "REPLACE ME"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['db'] }}"
  when: hostvars[item]['site'] == hostvars[inventory_hostname]['site']

# Restart service --------------------------------------------------------------
- name: Restarting service
  ignore_errors: true
  systemd:
    name: haapp
    state: restarted
    daemon_reload: yes
    enabled: yes

# Smoke test -------------------------------------------------------------------
- name: Smoke test
  command: "/opt/test.sh {{ inventory_hostname }}"
  ignore_errors: true
  register: cmd_result
