---
- hosts: app
  become: yes
  serial: 1
  pre_tasks:
    - name: disable server in server pool
      shell: echo "disable server {{ inventory_hostname }}/{{ hostvars[inventory_hostname]['ansible_host'] }}" | socat stdio /var/lib/haproxy/stats
      delegate_to: "{{ item }}"
      with_items: "{{ groups['lb'] }}"
  post_tasks:
    - name: enable server in server pool
      shell: echo "enable server {{ inventory_hostname }}/{{ hostvars[inventory_hostname]['ansible_host'] }}" | socat stdio /var/lib/haproxy/stats
      delegate_to: "{{ item }}"
      with_items: "{{ groups['lb'] }}"
  roles:
    - app
