---
- hosts: all
  gather_facts: false
  tasks:
    - name: set fact
      set_fact:
        rollback: false


- hosts: app
  become: yes
  tasks:
    - name: Create group with blue/green machines
      group_by:
        key: "{{ group }}-app"
    - name: deploy test script  # REMOVE REMOVE REMOVE!
      copy:
        src: test.sh
        dest: /opt/test.sh
        mode: 0777



# Blue Deployment --------------------------------------------------------------
- hosts: blue-app
  become: yes
  strategy: linear
  tasks:
    - name: Include deployment tasks
      include_tasks: deployment_tasks.yml

    - name: test
      debug:
        msg: "{{ play_hosts | map('extract', hostvars, 'cmd_result') | selectattr('failed', 'equalto', true) | list }}"

    - name: Restoring blue from backups
      include_tasks: rollback_tasks.yml
      when: play_hosts | map('extract', hostvars, 'cmd_result') | selectattr('failed', 'equalto', true) | list | count > 0



# Switch to blue environment ---------------------------------------------------
- hosts: lb
  become: yes
  tasks:
    - name: Add blue servers to load balancers
      command: echo "yaay"
      when: hostvars[item]['group'] == 'blue' and rollback
      with_items: "{{ groups['app'] }}"

    - name: Remove green servers from load blancers
      command: echo "yaay"
      when: hostvars[item]['group'] == 'green' and rollback
      with_items: "{{ groups['app'] }}"




# Full deployment confirmation -------------------------------------------------
#- hosts: all
#  vars_prompt:
#    name: "confirmation"
#    prompt: "Continue deployment? (yes/no)"
#    default: "no"
#    private: no
#  tasks:
#    - name: set fact
#      set_fact:
#        rollback: "{{ confirmation != 'yes' }}"

# Restore if rollback is requested ---------------------------------------------
- hosts: lb
  become: yes
  tasks:
    - name: Add green servers to load balancers
      command: echo "yaay"
      when: hostvars[item]['group'] == 'green' and rollback
      with_items: "{{ groups['app'] }}"

    - name: Remove blue servers from load blancers
      command: echo "yaay"
      when: hostvars[item]['group'] == 'blue' and rollback
      with_items: "{{ groups['app'] }}"

- hosts: blue-app
  tasks:
    - name: Rollback
      include_tasks: rollback_tasks.yml
      when: rollback




# Green Deployment -------------------------------------------------------------
- hosts: green-app
  become: yes
  tasks:
    - name: Deploy to green
      include_tasks: deployment_tasks.yml

    - name: connect to load balancer
      command: echo "connecting"
